//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandByHand
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditDirection
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string Name_Direction { get; set; }
        public int Mentor_ID { get; set; }
        public int Direction_ID { get; set; }
    }
}
